name: Build Stable ISOs
on:
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: 'Upload ISOs as job artifacts'
        type: boolean
        default: true
      upload_r2:
        description: 'Upload ISOs to Cloudflare R2'
        type: boolean
        default: false
  #schedule:
    #- cron: '0 2 1 * *'

jobs:
  build-iso-stable:
    name: Build Stable ISOs
    uses: ./.github/workflows/reusable-build-iso-anaconda.yml
    secrets: inherit
    with:
      image_tag: stable
      upload_artifacts: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_artifacts || false }}
      upload_r2: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_r2 || true }}
