name: Renovate
on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/renovate.json5'
      - '.github/workflows/renovate.yml'

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@0b17c4eb901eca44d018fb25744a50a74b2042df # v46.1.4
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
