name: Reusable Build ISO
on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        default: stable
      upload_artifacts:
        type: boolean
        default: false
      upload_r2:
        type: boolean
        default: true
    secrets:
      R2_ACCESS_KEY_ID_2025:
        required: false
      R2_SECRET_ACCESS_KEY_2025:
        required: false
      R2_ENDPOINT_2025:
        required: false

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create empty flatpak list
        id: flatpaks
        run: |
          FILE="$(mktemp)"
          : > "$FILE"
          echo "file=$FILE" >> "$GITHUB_OUTPUT"

      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@main
        with:
          image-ref: ghcr.io/humocs-man/fluffy-pancake:${{ inputs.image_tag }}
          flatpaks-list: ${{ steps.flatpaks.outputs.file }}
          hook-post-rootfs: ${{ github.workspace }}/iso/enable_anaconda.sh
          kargs: NONE
          builder-distro: fedora

      - name: Rename ISO
        run: |
          mkdir -p output
          mv "${{ steps.build.outputs.iso-dest }}" output/fluffy-pancake-${{ inputs.image_tag }}.iso
          sha256sum output/*.iso | tee output/CHECKSUMS

      - name: Upload Artifacts
        if: inputs.upload_artifacts
        uses: actions/upload-artifact@v5
        with:
          name: fluffy-pancake-iso
          path: output
